baseURL: "https://building.lokeshkr.com"
languageCode: en-us
title: Lokesh Kumar
theme: PaperMod

params:
  homeInfoParams:
    Title: "Namaskaram ðŸ™ , I'm Lokesh"
    Content: >
      I am a Blockchain Developer who loves 
      building Decentralized Applications and systems using Blockchain 
      Technology. I am always looking to learn and expand my skill set.
  assets:
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-touch-icon.png"
  socialIcons:
    - name: GitHub
      url: https://github.com/codeTIT4N
    - name: LinkedIn
      url: https://www.linkedin.com/in/lokesh-kumar-nalot-0baa691b9
    - name: Twitter
      url: https://twitter.com/lokeshtweets_
    - name: email
      url: mailto:lokeshkumar636@yahoo.com
    - name: telegram
      url: https://t.me/lokesshk
    # - name: tech-blog
    #   url: http://blog.lokeshkr.com
    - name: YouTube
      url: https://www.youtube.com/@LokeshWritesCode/videos

menu:
  main:
    - identifier: portfolio
      name: Portfolio
      url: /portfolio
      weight: 10
    # - identifier: telegram
    #   name: Ping Me
    #   url: https://t.me/lokesshk
    #   weight: 20
    - identifier: tech-blog
      name: Tech Blog
      url: https://blog.lokeshkr.com
      weight: 30
